### ISSUE TITLE
Is this repository the final version?

### ISSUE THREAD

**Issue by alphadl** [baosongyang/WRD#1]
Great work, but I find that the implementation of [RNMT+](https://www.aclweb.org/anthology/P18-1008) and [DiSAN](https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/viewFile/16126/16099) are not complete~ Specifically, the implementation of RNMT+ only apply their encoder side (i.e., <https://github.com/baosongyang/WRD/blob/master/thumt/models/RNN_p.py#L49-L88>) and it seems that DiSAN (<https://github.com/baosongyang/WRD/blob/master/thumt/models/transformer_di.py>) is unchanged compared with transformer_ori.

Will this repository continue to update after paper releasing? Thx

**Comment by baosongyang** [comment]
Thanks for your attention! 
1. About RNMT+: Since our work focuses on assessing the abilities of encoders to learn word order, we merely re-implemented model variants upon the source-side of Transformer. Details can be learned in our paper, which have been released at (https://arxiv.org/pdf/1906.00592.pdf).
2. Considering DiSAN: transformer_ori.py and transformer_di.py call different attention function, being writing in (https://github.com/baosongyang/WRD/blob/master/thumt/layers/attention.py) and (https://github.com/baosongyang/WRD/blob/master/thumt/layers/attention_di.py), respectively. 
3. We would like to continue to update this repository if there exists problem or new properties.

**Comment by alphadl** [comment]
I see~ Thanks for your kind and detailed reply 👍
